### ISSUE TITLE
"attachments" shortcode broken under Hugo 0.73.0

### ISSUE THREAD

**Issue by beowabbit** [vjeantet/hugo-theme-docdock#206] opened 2020-07-10 03:49 UTC
The "attachments" shortcode seems to be broken under Hugo 0.73.0 -- it generates the HTML for a list, but that HTML is emitted preformatted (so not rendered as HTML) and without the "Attachments" heading.  Works fine in 0.48 (which we were trying to upgrade from).  This is with the latest version of DocDock, but we first noticed it with `2c9ccd18ef225b71352479b154255f2a3cfe492f` (and upgrading to the latest DocDock didn't make a difference).

I've got a trivial site that shows the problem (although it looks to me like _any_ use of `attachments` breaks in 0.73.0 and works in 0.48) at https://github.com/beowabbit/docdock-attachments-busted .

Here's a working screenshot under 0.43:
![working-under-0 48](https://user-images.githubusercontent.com/1036760/87114537-d5dcce00-c23e-11ea-8558-42e5a59415d6.png)

Here's a broken screenshot under 0.73.0:
![broken-under-0 73](https://user-images.githubusercontent.com/1036760/87114549-dffecc80-c23e-11ea-87ac-9f26dc5fd93e.png)

**Comment by divinerites** [comment] 2020-07-10 07:15
Indentation and goldmark should be the cause.

For example, see https://discourse.gohugo.io/t/0-60-0-goldmark-html-indentation-in-partial-shortcode-wrapped-in-pre-code/22019/10

**Comment by beowabbit** [comment] 2020-07-10 12:53
(I can't get to that discourse.gohugo.io link -- which is fine; just wanted to make sure the link wasn't intended for me.)

**Comment by beowabbit** [comment] 2020-07-10 13:11
I can confirm that this goes away if I force Markdown with

```
[markup]
defaultMarkdownHandler = "blackfriday"
```

in `config.toml`.  So I have a workaround that lets us upgrade Hugo to 0.73.  Sounds like it's useful to get DocDock working with Goldmark, though, and in the meantime adding a note to the documentation about how to force `blackfriday` rendering if you have trouble with shortcodes might be helpful.

**Comment by beowabbit** [comment] 2020-07-10 13:46
I'm testing the other shortcodes; so far, `expand` is busted in a similar way (raw HTML is wrapped in `<pre><code>`...`</code></pre>`) and `children` is busted differently (with children's titles emitted as plain text, not list-formatted, and without any links).

I'll update the repo with a full set of examples calling out the broken ones when I'm finished.

**Comment by divinerites** [comment] 2020-07-10 14:17
> (I can't get to that discourse.gohugo.io link -- which is fine; just wanted to make sure the link wasn't intended for me.)

This link is public.

The main point is  this is caused by using goldmark (used by default) and indentation code.

So try to do not change for blackfriday **but flatten your code** by removing indentations. Will work fine.

**Comment by beowabbit** [comment] 2020-07-10 14:43
@divinerites When I try to go to https://discourse.gohugo.io/t/0-60-0-goldmark-html-indentation-in-partial-shortcode-wrapped-in-pre-code/22019/10 I get "Oops! That page doesn’t exist or is private."

At this point I understand the problem, but the `children`, `attachments`, and `expand` shortcodes included in DocDock all produce HTML with indentation, so the fix needs to be in DocDock (although I could clone the shortcodes in my site and make versions that worked).

It's also kind of annoying that it seems not to be possible for a shortcode to emit indented, easily legible HTML if it's going to be rendered by Goldmark (but of course that's outside the control of DocDock).

I've updated my repo at https://github.com/beowabbit/docdock-attachments-busted to include tests for all the other DocDock shortcodes except for revealjs (which I didn't test).

**Comment by divinerites** [comment] 2020-07-10 15:12
No. You have to flatten **the code** in your partial & shortcode with the problem.

**Comment by divinerites** [comment] 2020-07-10 15:13
> @divinerites When I try to go to https://discourse.gohugo.io/t/0-60-0-goldmark-html-indentation-in-partial-shortcode-wrapped-in-pre-code/22019/10 I get "Oops! That page doesn’t exist or is private."

You have to be logged in. Strong advice if you use gohugo is to be on this forum. *huge* source of information.

**Comment by beowabbit** [comment] 2020-07-10 21:20
> No. You have to flatten **the code** in your partial & shortcode with the problem.

You mean the code of the shortcode, right?  The shortcode is part of the theme.  So I could fork the theme and flatten what the shortcode emits, but if I'm just using the upstream `hugo-theme-docdock` there's nothing I can do to flatten the results of the shortcode, is there?  Or is there some special syntax to generate the HTML with a shortcode and then flatten it before it gets to the Markdown renderer that I'm supposed to be using?  (I wouldn't have taken people's time by filing this issue if I didn't think other people might run into the same problem.)

(BTW, I went ahead and created an account on discourse.gohugo.io but still get told “Oops! That page doesn’t exist or is private.”)

**Comment by divinerites** [comment] 2020-07-10 21:33
> You mean the code of the shortcode, right? The shortcode is part of the theme.

yes. 

just copy the code from the theme and put it in your `layout/sortcode/ and/or `layout/partials/`. No need to fork anything

**Comment by vjeantet** [comment] 2020-07-14 14:21
Hello, i faced the same issue, resolved by adding this param in 

config.toml
```toml
[markup.goldmark.renderer]
unsafe = true
```

or 
config.yml
```yml
markup:
  goldmark:
    renderer:
      unsafe: true
```

source : https://discourse.gohugo.io/t/hugo-0-60-0-raw-html-omitted-issue/22010/2

**Closed** 2021-06-15 09:55 UTC
