### ISSUE TITLE
text after alert shortcode does no render markdown properties

### ISSUE THREAD

**Issue by ball-b-doc** [vjeantet/hugo-theme-docdock#193] opened 2019-05-10 13:13 UTC
I am writing
{{% alert theme="danger" %}} **Important !** abc 

* item 1
* item 2 

**bold-text**  {{% /alert %}}

The danger alert box is being used, but non of the other markdown properties is interpreted.
result is like:
**Important !** abc * item 1* item 2 **bold-text**

within the alert box.

Any idea?
I have tried this with different files and boxes. Also installed hugo and Docdock on another Mac, but with the same result.
using 
Hugo Static Site Generator v0.55.4/extended darwin/amd64 BuildDate: unknown

**Comment by rbanks54** [comment] 2019-07-04 00:21
Applies to Panel as well

**Comment by rbanks54** [comment] 2019-07-04 00:50
This thread helps clarify things: https://discourse.gohugo.io/t/misunderstanding-of-shortcode-syntax-in-0-55/18538

The problem is caused by the alert shortcode containing HTML tags.

Changing the shortcode to use 
```
{{.Inner | markdownify}}
```
instead of just `{{.Inner}}` will fix the problem. The other shortcodes are likely to be impacted the same way

**Comment by Marthym** [comment] 2019-10-13 17:52
Fixed by 9e7631c69770

**Closed by Marthym** 2019-10-13 17:52 UTC
